{"name": "test_validate_csv[C:\\Users\\vybor\\PycharmProjects\\Yadro\\csv\\test_invalid_character.csv]", "status": "passed", "description": "Checking csv_files_invalid", "parameters": [{"name": "path_invalid", "value": "'C:\\Users\\vybor\\PycharmProjects\\Yadro\\csv\\test_invalid_character.csv'"}], "start": 1675003855650, "stop": 1675003855650, "uuid": "466e0889-29d4-48f1-a894-6fb3fd64c002", "historyId": "bb9d0a918439ef0e4cfa6c2cee896541", "testCaseId": "6d42316c1b8fbf2f0a4906cb3ebfc5fc", "fullName": "tests.test_validate_csv.TestCSV#test_validate_csv", "labels": [{"name": "story", "value": "A correct error was received with invalid values in csv"}, {"name": "epic", "value": "Test create place"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_validate_csv"}, {"name": "subSuite", "value": "TestCSV"}, {"name": "host", "value": "DESKTOP-19E6A29"}, {"name": "thread", "value": "5412-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_validate_csv"}]}